name: Continuous Integration

on:
  push:
    branches:
      - main  # Run CI on every push to the main branch
  pull_request:
    branches:
      - main  # Run CI on pull requests targeting the main branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest  # Use an Ubuntu environment for the CI job

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      # Step 3: Install SQLite3 (required for database checks)
      - name: Install SQLite3
        run: sudo apt-get install -y sqlite3

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn  # Add any other required Python libraries

      # Step 5: Make the test.sh script executable
      - name: Make test.sh executable
        run: chmod +x ./test.sh

      # Step 6: Run the tests
      - name: Run tests
        run: ./test.sh

      # Optional Step: Cache dependencies to speed up future CI runs
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
