name: Run Tests

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # You can specify your Python version here

    # Step 3: Install SQLite3
    - name: Install SQLite3
      run: sudo apt-get install sqlite3

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Make test.sh executable
    - name: Make test.sh executable
      run: chmod +x ./test.sh  # Ensure the correct path to your script

    # Step 6: Run the tests
    - name: Run tests
      run: ./test.sh
