name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install SQLite3
      run: sudo apt-get install sqlite3 -y

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib seaborn kaggle

    - name: Set up Kaggle API credentials
      run: |
        mkdir -p ~/.config/kaggle
        echo "{\"username\":\"dhavalmulani\",\"key\":\"071cf689d9832b1fa34ebbdb48022293\"}" > ~/.config/kaggle/kaggle.json
        chmod 600 ~/.config/kaggle/kaggle.json

    - name: Make test.sh executable
      run: chmod +x ./project/test.sh

    - name: Run tests
      run: ./project/test.sh
